### PR TITLE
BatchClaimRewards on twTap [`CU-86dtv4tnx`]

### PR DESCRIPTION
**Pull request by cryptotechmaker**

### CODE REVIEW

**Comment by cryptotechmaker** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tap-token/230?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#230** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tap-token/230?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#229** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tap-token/229?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @cryptotechmaker and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by 0xRektora** [comment]
Task linked: [CU-86dtv4tnx BatchClaimRewards on twTap](https://app.clickup.com/t/86dtv4tnx)

**Review by maarcweiss — APPROVED** [review]
Looks good

**Comment by 0xRektora** [comment]
### Merge activity

* **Jun 22, 2:52 PM EDT**: @0xRektora started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Tapioca-DAO/tap-token/230).

**Pull request merged**
